# Generated by Django 4.2.29 on 2026-07-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_passwordresetotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("owner", "Owner"),
                ],
                default="teacher",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customeruser",
            name="role_SW",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("owner", "Owner"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
