"""
Django settings for pollme project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
from pathlib import Path
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from datetime import timedelta
import datetime
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


from dotenv import load_dotenv
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'x*za6xf&_80ofdpae!yzq61g9ffikkx9$*iygbl$j7rr4wlf8t'
SECRET_KEY = "x*za6xf&_80ofdpae!yzq61g9ffikkx9$*iygbl$j7rr4wlf8t"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['EduPulse.pythonanywhere.com','169.58.105.106','shulefasta.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',  #swagger documentation
    #'ckeditor',
    'djoser',
    'django_apscheduler',
    #'ckeditor_uploader',
    'corsheaders', #to connect django and react
    'App',
    'MyTemplatesApp',

    'AddAppViewSets',
    'accounts.apps.AccountsConfig',
    'import_export',
    'django_extensions'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project.wsgi.application'
AUTH_USER_MODEL="App.CustomerUser"

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'shulefastadb',
        'USER':'shulefasta',
        'PASSWORD':'Dimoso@9898',
        'HOST':'localhost',
        'PORT':'',
    }
}



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'microfinancedb',
#         'USER':'microfinance',
#         'PASSWORD':'Dimoso@9898',
#         'HOST':'localhost',
#         'PORT':'',
#     }
# }




# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Dhaka'
# #TIME_ZONE = 'African/dar_es_salaam'

# USE_I18N = True

# USE_L10N = True

# USE_TZ = True



TIME_ZONE = 'Africa/Dar_es_Salaam'
#TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_TZ = True



# STATIC_URL = '/static/'


# STATIC_ROOT = BASE_DIR / "MyTemplatesApp/static"


STATIC_URL = '/static/'

# Hapa ndipo Django itatupa files zote wakati wa 'collectstatic'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Hapa ndipo unapoeka picha/CSS zako mwenyewe
STATICFILES_DIRS = [
    BASE_DIR / "MyTemplatesApp/static",
]

print("STATICFILES_DIRS path:", BASE_DIR / "MyTemplatesApp/static")

MEDIA_URL = "/media/"
MEDIA_ROOT= BASE_DIR / "media"


JAZZMIN_SETTINGS = {
    # HAPA NDIPO UNAFICHA APPS NA MODELS
    "hide_apps": ["django_apscheduler"], # Weka jina la app unayotaka kuificha

    "hide_models": [
        "auth.Group",            # Ficha Group
        "django_apscheduler.DjangoJob", # Ficha job specific
        "django_apscheduler.DjangoJobExecution",
        "authtoken.Token",                # Hii ndio inaficha 'Tokens'
        "authtoken.TokenProxy",           # Hii inaficha 'Auth Token' (kama ipo)
    ],


    # Title ya dashboard yako
    "site_title": "School Admin",
    "site_header": "DASHBOARD",
    "site_brand": "DASHBOARD",

    "custom_css": "css/custom.css", # Hii faili utatengeneza

    # ONGEZA HII SEHEMU
    "login_logo": "images/icon.png", # Hii ndio logo ya login
    #"login_logo_dark": "images/icon2.png",

    # Logo (Ikiwezekana weka logo kwenye static folder yako)
    "site_logo": "images/icon.png",

    # Welcome text kwenye login page
    "welcome_sign": "Get Back to Shule Fasta",

    # Copyright
    "copyright": "Shule Fasta System Ltd",

    # Customize menu ya kushoto (Hapa ndipo unapo-group models zako)
    "order_with_respect_to": ["School", "CustomerUser", "Student", "Teacher"],

    # Icons kwa ajili ya models (Jazzmin inatumia FontAwesome)
   "icons": {
        "App.school": "fas fa-school",
        "App.customeruser": "fas fa-user-tie",
        "App.academicyear": "fas fa-calendar-alt",
        "App.classroom": "fas fa-chalkboard",
        "App.stream": "fas fa-random",
        "App.subject": "fas fa-book",
        "App.student": "fas fa-user-graduate",
        "App.studentenrollment": "fas fa-file-contract",
        "App.teacher": "fas fa-chalkboard-teacher",
        "App.feestructure": "fas fa-money-bill-wave",
        "App.feepayment": "fas fa-receipt",
        "App.examcategory": "fas fa-tags",
        "App.exam": "fas fa-pen-nib",
        "App.result": "fas fa-poll",
        "App.attendance": "fas fa-user-check",
        "App.timetable": "fas fa-clock",
        "App.gradingsystem": "fas fa-sort-numeric-down",
        "App.schoolevent": "fas fa-calendar-day",
        "App.reportsent": "fas fa-paper-plane",
        "App.studentbehaviour": "fas fa-smile",
        "App.parentcomment": "fas fa-comments",
        "App.teacherscheme": "fas fa-book-open",
        "App.passwordresetotp": "fas fa-key",
    },

    # Style ya dashboard
    "show_ui_builder": False, # Hii itakupa button ya ku-customize UI kwa urahisi kwenye admin
}

# Settings za theme (Chagua rangi unayopenda)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark", # Badilisha iwe light
    "accent": "accent-navy",         # Chagua rangi isiyo na bluu sana
    "navbar": "navbar-dark navbar-dark", # Navbar nyeupe
    "skin": "sidebar-dark-primary",  # Sidebar nyeusi
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'dimosodeveloper@gmail.com'
EMAIL_HOST_PASSWORD = 'gwcxijkypfzgbtkk'
EMAIL_USE_TLS = True




# M- SMART
# API KEY = 7eb965f631d2f009
# SECRET KEY = ODFmOTRmMzMzMzcyNTlhN2NjY2UxOWI2MTNiZDhjODAyNzAwNTYzODYxYzYxMzQ4N2MxNDhiOTVjYTBlZWQyNQ==